### ISSUE TITLE
connected graph compulsory for HOP-Rec?

### ISSUE THREAD

**Issue by tearsofmars** [cnclabs/smore#38]

**Comment by chihming** [comment]
Yes for general cases, as HOP-Rec searches indirectly connected by random walk. If you'd like to apply it to other kinds, you can show me some examples of your data. Maybe I can help figure out how to apply it to your data.

**Comment by tearsofmars** [comment]
Thanks for getting back to me promptly! Really appreciated!! Don't have a specific dataset in mind. Rather, it was a general question raised after reading your deck/papers (and other RW based papers).
