### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc' what():  std::bad_alloc

### ISSUE THREAD

**Issue by shivinsaluja** [cnclabs/smore#39]
Whenever I try to run the code with any model I get this error - 

**terminate called after throwing an instance of 'std::bad_alloc'
what():  std::bad_alloc**

I think this is an issue in proNet.cpp. Please revert if you find a suitable solution.

**Comment by chihming** [comment]
Could you show me the input and the command you testes? so that I can reproduce the issue
