### ISSUE TITLE
About the output

### ISSUE THREAD

**Issue by 0215Arthur** [cnclabs/smore#41]
Dear authors:

I have a question about the output file, do it follow the vertex order in train file?  And includes the user   and item representation?

**Comment by chihming** [comment]
1. Since the graph reader indexes the vertexes line by line, I guess the representations will be saved in order (not confirmed).
2. Most of the algorithms will include ALL of the vertex embedding.

**Comment by 0215Arthur** [comment]
OK, thank you very much.
