### ISSUE TITLE
About the parameters setting

### ISSUE THREAD

**Issue by 0215Arthur** [cnclabs/smore#42]
Hi ! 
The parameter settings [walk steps] seems no working.
just like the command line outputs as follows:
 
> + ./cli/hoprec -train train_6.txt -field field6.txt -sample_times 200 -walk_step 50 -save ./res/hop6.txt -dimensions 64 -threads 10
Connections Preview:
	# of connection:	339160
Connections Loading:
	Progress:		100.00 %
	# of vertex:		69060
Build the Alias Method:
	Reconstructing Graph ...
	Building Alias Tables ...
	Finished.
Meta Data Preview:
	# of meta data:		69060
Meta Data Loading:
	Progress:		100.00 %
	# of field:		2
Init Field Index:
	Finished.
Model Setting:
	dimension:		64
Model:
	[HBPR]
Learning Parameters:
	sample_times:		200
	alpha:			0.025
	walk steps:		5
	workers:		10

Is it an error?

**Comment by 0215Arthur** [comment]
sorry, I found that it's my error.

**Comment by chihming** [comment]
BTW, the walk step is used to get the high-order neighbors. For recommendation problem, 5 is already a big number. I usually set it by 2 or 3.

**Comment by 0215Arthur** [comment]
> BTW, the walk step is used to get the high-order neighbors. For recommendation problem, 5 is already a big number. I usually set it by 2 or 3.

OK， thank you very much.
