### ISSUE TITLE
Question about code of the baseline Deepwalk 

### ISSUE THREAD

**Issue by yycg** [cnclabs/smore#44]
Dear Authors,

Recently I am reading your source code and find it helpful with my research. May I ask you a question that I don't quite understand.

In Skip-Gram process (line 99 of DeepWalk.cpp, line 766 of proNet.cpp), you assign labels of negative samples to 0. Then in update Pairs process (line 100 of DeepWalk.cpp, lines 2659 and 1702 of proNet.cpp), you seem to ignore the labels 0 and retake negative sampling. Could you please give me some hints for better understanding your intention?

Thank you!

**Comment by chihming** [comment]
Sorry for my late reply. That's indeed a confused implementation. In the current code, I sample the POSITIVE pairs from the "Skip-Gram process" you mentioned, and then to do NEGATIVE sampling in "update Pairs process" you mentioned. It's still possible to sample the negatives from "Skip-Gram process".

**Comment by yycg** [comment]
Thank you very much for your reply. I didn't realize that you assign 0 to nagetive_samples in Skip-Gram process.
